---
title: "Voronoi_Practice"
author: 'Nathan'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggvoronoi)
library(tidyverse)
library(lubridate)
set.seed(45056)
x <- sample(1:200,100)
y <- sample(1:200,100)
points <- data.frame(x, y,
                     distance = sqrt((x-100)^2 + (y-100)^2))

ggplot(points) +
  geom_voronoi(aes(x,y,fill=distance))
```

```{r}
# library(ggmap)
# api <- ""
# register_google(key=api)
# oxford_map <- get_googlemap(center = c(-84.7398373,39.507306),zoom = 15,key=api)
# bounds <- as.numeric(attr(oxford_map,"bb"))
# map <-
#   ggmap(oxford_map,base_layer = ggplot(data=oxford_bikes,aes(x,y))) +
#         xlim(-85,-84)+ylim(39,40)+
#         coord_map(ylim=bounds[c(1,3)],xlim=bounds[c(2,4)]) +
#         theme_minimal() +
#         theme(axis.text=element_blank(),
#               axis.title=element_blank())
# map + geom_path(stat="voronoi",alpha=.085,size=.25) +
#       geom_point(color="blue",size=.25)
```

```{r}
# df <- read_csv(here::here('Uber-dataset','uber-raw-data-apr14.csv.zip'))
# df <- df %>% 
#   filter(mday(parse_date_time(`Date/Time`,"mdy_hms"))==1) %>% 
#   select(Lat, Lon) %>% 
#   distinct()
# df
# df <- data.frame(df)
# ggplot(df) +
#  xlim=c(-75,-72)+ylim=c(40,42)+
#  scale_x_continuous(limits = c(-74.1, -73.9))+
#  scale_y_continuous(limits = c(40.6, 40.8))+
#    geom_point(aes(x='lon',y='lat'))
# ggplot(data, aes(x='lon',y='lat'))+
#   geom_voronoi()

# vpoly <- voronoi_polygon(df,x="Lon",y="Lat")
# geom_path(data=fortify_voronoi(vpoly),aes(Lat,Lon))
```

```{r}
df <- read_csv(here::here('Uber-dataset','uber-raw-data-Jan22.csv')) %>% 
#  filter(mday(mdy_hms(`Date/Time`))==1) 
#  filter(hour(parse_date_time(`Date/Time`,"mdy_hms"))==0)
#  mutate(hourtime=hour(`Date/Time`))
#  mutate(day=mday(parse_date_time(`Date/Time`,'%m/%d/%Y %I:%M:%S %p')))
  mutate(d=parse_date_time(`Date/Time`,"%m/%d/%Y %H:%M")) %>% 
  filter(mday(d)==1&hour(d)==0&Base=="B02512") %>% 
  select(Lat, Lon) %>% 
  distinct()
df
ggplot(df)+
  geom_point(aes(x='lon',y='lat'))
ggplot(data=df, aes(x='lon',y='lat'))+
  geom_voronoi()
```

